### ISSUE TITLE
Improved IDE UX

### ISSUE THREAD

**Issue by sebastianconcept** [amber-smalltalk/amber-contrib-legacy#3]
- Typography issues
- Poor contrast issues
- Focus issues
- Lack of search keyboard shortcut
- Tab close area too small
- SUnit button alignment
- Horizontal arrow keys should change the pane in focus (on Browser and SUnit)
- Vertical arrow keys should change the selected list item when focus is in a list pane
- Save button disabled on pristine
- Marking changed packages
- Drag and drop to categorize methods
- Select and change theme easily and persist the preference on localStorage
- Change theme to be dark by default

**Comment by philippeback** [comment]
Question: do you have a version with all of these things?

**Comment by herby** [comment]
Technical: shouldn't they all be different issues? Or, if you think legacy IDE is worth developing and supporting, shouldn't it have repo on its own (amber-attic was, well, an attic with old things put away)?

Personal: until you do easy theme selection, no dark theme by default. It's in bottom of page. Pages are often bright (and they are bright also by default). Dark IDE in bright page is not good thing.

**Comment by sebastianconcept** [comment]
Hi guys.
Here some elaboration on the motivation:
https://medium.com/@sebastianconcpt/improving-the-amber-experience-26764d5d578

@herby yes maybe the dark as default can be reviewed, I give you that. But to make it right we need to at least make the bright one to be good (the current one is catastrophic)

I'd love to see the IDE in its own repo (great idea)

**Comment by sebastianconcept** [comment]
@philippeback I have some in a private app, and I'm considering in bothering myself in start sharing it. But I need to have an idea on how much receptiveness or friction this might have to face (hence the public post discussing about it).

If you guys like that please display it there so we increase the chances to make it happen

**Comment by hhzl** [comment]
Great idea to improve the legacy IDE.  I assume your private app you did is a fork of the legacy IDE?

I use it more often than Helios and would appreciate improvements on it.

**Comment by hhzl** [comment]
@sebastianconcept  I welcome your effort to reverse the trend of putting the old IDE into an attic. This means getting it down from the attic, dust if off and enhance it. Great. Small steps are very fine. Take your time.

**Comment by hhzl** [comment]
We should create a new repository and move the classic IDE to it.

**Comment by herby** [comment]
But they are unrelated to the IDE (and to each other as well).

**Comment by hhzl** [comment]
Yes. But is it worth the effort?

**Comment by sebastianconcept** [comment]
Hopefully I make the decision simple for you: after the Classic IDE repo gets created I either (1) push commits related to the mentioned issues (and/or others) to it or (2) I fork it and do it on my fork for me and whoever might want to use it

**Comment by sebastianconcept** [comment]
@hhzl based on the data we have so far in the poll, the answer to that is: yes.

**Comment by NicolasPetton** [comment]
IMO the old IDE has a poor design and is hard to maintain and evolve, not to mention that it lacks so many features that it will take a huge effort to catch up with Helios.

Why not improve Helios instead? Is there something so wrong with it that it cannot be fixed?

**Comment by philippeback** [comment]
Le 3 févr. 2015 21:29, "Nicolas Petton" <notifications@github.com> a écrit :
>
> IMO the old IDE has a poor design and is hard to maintain and evolve, not
to mention that it lacks so many features that it will take a huge effort
to catch up with Helios.
>
> Why not improve Helios instead? Is there something so wrong with it that
it cannot be fixed?

Helios is damn slow.
Maybe this is due to announcements.

Also, we need shorter keybindings. But a lot do conflict with the browser
normal bindings if we do that. Busy looking into that.

I would like an option to embed it in a page. That is possible as I saw an
example on line.

For me I am on the Helios improvement path. But having both is not an issue
but allows exploration of more than one way to do things.

Yes this is additional effort but we need real cases like that to learn the
way to do things with Amber.

Phil

**Comment by sebastianconcept** [comment]
@NicolasPetton I elaborate [here](https://medium.com/@sebastianconcpt/improving-the-amber-experience-26764d5d578) about why Helios didn't work for me and some, kind of easy things to do that will render significant improvements in the classic IDE.

And there is data from [this poll](http://goo.gl/forms/DZ2djBRW9E) that supports the strategy

**Comment by NicolasPetton** [comment]
@sebastianconcept I'm sorry, I strongly disagree with you here. 

Getting the old IDE in a decent shape with half of the features Helios has will be a *huge* work. Not to mention splitting efforts in a small community is IMO not a good idea. Do not under-estimate the effort it will take to redo it. Because that's what this is about, redoing the same, again. Maybe slightly differently, but that's it. And you will face the same issues and technical problemes that were faced when developing Helios.

In your post @sebastianconcept you do not exactly say what it is that you don't like in Helios. 

You want context menus? That should be doable in a couple of hours. Helios uses commands, applyable in contexts, so it's easy to do. No keyboard required.

There's no bottom pane support? That can be added in less than 10 loc (and it was there at some point).

Speed is an issue? Well, it wasn't for me, but if it is, it should be fixed. And that will take *much* less time than making the old IDE as good as Helios in all other aspects.

Maybe I'm missing something crucial, but for me as I see it currently this would just be a huge waste.

**Comment by herby** [comment]
Old, closing.
